// <auto-generated />
namespace Aphrie.Project.DAL.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class login1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(login1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008070004538_login1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
