// <auto-generated />
namespace Aphrie.Project.DAL.SQLServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class followers1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(followers1));
        
        string IMigrationMetadata.Id
        {
            get { return "202008091155485_followers1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
